import { useMemo, useState } from "react";
import { activities, zones } from "../data/demoData";
import type { FieldActivityDemo, RecoveryZoneDemo } from "../types";
import { Icon } from "../components/Icons";
import { PrototypeModal } from "../components/PrototypeModal";
import { PrototypeShell } from "../components/PrototypeShell";
import { RecoveryUpdateCard } from "../components/RecoveryUpdateCard";
import { SummaryStrip } from "../components/SummaryStrip";
import { ZoneDetailModal } from "../components/ZoneDetailModal";

export function VolunteerWorkspace() {
  const [activity, setActivity] = useState<FieldActivityDemo | null>(activities[0]!);
  const [zoneDetail, setZoneDetail] = useState<RecoveryZoneDemo | null>(null);
  const [action, setAction] = useState<string | null>(null);
  const [location, setLocation] = useState("All locations");
  const [priority, setPriority] = useState("All priorities");
  const [availability, setAvailability] = useState("Any activity status");
  const [stage, setStage] = useState("All stages");
  const filteredZones = useMemo(()=>zones.filter(zone=>(location==="All locations"||zone.province===location)&&(priority==="All priorities"||zone.priority===priority)&&(availability==="Any activity status"||(availability==="Activities available"?zone.activityAvailable:!zone.activityAvailable))&&(stage==="All stages"||zone.stage===stage)),[location,priority,availability,stage]);
  const summary=[
    {label:"My followed zones",value:"02",note:"Demo profile",icon:"follow" as const},
    {label:"Upcoming activities",value:"03",note:"Verified organisations",icon:"activity" as const},
    {label:"My contributions",value:"01",note:"Supporting observation",icon:"observe" as const},
    {label:"Recovery updates",value:"01",note:"New monitoring example",icon:"recovery" as const},
  ];
  return <PrototypeShell mode="volunteer"><main className="rc-main">
    <section className="rc-volunteer-hero"><span className="rc-kicker rc-kicker--orange">Community recovery action</span><h1>Help recovery<br/>where it is needed.</h1><p>Follow expert-reviewed zones, join activities approved by verified organisations, record what you see and return to the recovery story.</p><div className="rc-flow">{[["follow","Discover"],["zone","View zone"],["people","Join"],["observe","Contribute"],["recovery","Follow recovery"]].map(([icon,label],i)=><div key={label}><span><Icon name={icon as "follow"}/></span><strong>0{i+1}</strong><small>{label}</small></div>)}</div></section>
    <SummaryStrip items={summary}/>
    <section className="rc-section"><div className="rc-section-head"><div><span className="rc-kicker">Choose where to engage</span><h2>Discover Recovery Zones</h2></div><span className="rc-demo-pill">Demo filters · no persistence</span></div><div className="rc-filters"><label>Location<select value={location} onChange={e=>setLocation(e.target.value)}><option>All locations</option>{[...new Set(zones.map(z=>z.province))].map(x=><option key={x}>{x}</option>)}</select></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}><option>All priorities</option><option>High Priority</option><option>Medium Priority</option></select></label><label>Activity<select value={availability} onChange={e=>setAvailability(e.target.value)}><option>Any activity status</option><option>Activities available</option><option>Monitoring only</option></select></label><label>Recovery stage<select value={stage} onChange={e=>setStage(e.target.value)}><option>All stages</option>{[...new Set(zones.map(z=>z.stage))].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="rc-zone-discovery">{filteredZones.map(zone=><article key={zone.id}><div className="rc-zone-map"><span>{zone.province}</span><i/><i/><i/></div><div className="rc-zone-discovery__body"><div><span className="rc-priority">{zone.priority}</span><span className="rc-status">{zone.stage}</span></div><h3>{zone.name}</h3><p>{zone.why}</p><dl><div><dt>Verified by</dt><dd>{zone.organisation}</dd></div><div><dt>What can I do?</dt><dd>{zone.activityAvailable?"Join a verified activity":"Follow monitoring updates"}</dd></div><div><dt>After I contribute</dt><dd>Evidence is reviewed and recovery remains trackable</dd></div></dl><button onClick={()=>setZoneDetail(zone)}>View Recovery Zone <Icon name="arrow"/></button></div></article>)}</div>{filteredZones.length===0&&<div className="rc-empty">No demo Recovery Zones match these filters.</div>}</section>
    <section className="rc-section"><div className="rc-section-head"><div><span className="rc-kicker">Approved by verified organisations</span><h2>Upcoming activities</h2></div><span className="rc-demo-pill">Demo workflow</span></div><div className="rc-card-grid">{activities.map(item=>{const zone=zones.find(z=>z.id===item.zoneId)!;return <button className={`rc-activity-card rc-activity-card--button${activity?.id===item.id?" is-selected":""}`} key={item.id} onClick={()=>setActivity(item)}><div className="rc-activity-card__top"><Icon name={item.type.includes("Observation")?"observe":"activity"}/><span>{item.date}</span></div><h3>{item.type}</h3><p>{zone.name}</p><div className="rc-capacity"><span><Icon name="people"/>{item.joined} / {item.capacity} joined</span><i><b style={{width:`${item.joined/item.capacity*100}%`}}/></i></div><small>Verified by {item.organisation}</small></button>})}</div></section>
    {activity&&<section className="rc-activity-detail"><div><span className="rc-kicker">Verified activity detail</span><h2>{activity.type}</h2><p className="rc-activity-detail__lead">{activity.description}</p><dl><div><dt>Date</dt><dd>{activity.date}</dd></div><div><dt>Location</dt><dd>{activity.location}</dd></div><div><dt>Organisation</dt><dd>{activity.organisation}</dd></div><div><dt>Coordinator</dt><dd>{activity.coordinator}</dd></div><div><dt>Capacity</dt><dd>{activity.joined} joined · {activity.capacity} total</dd></div></dl><h3>Requirements</h3><ul>{activity.requirements.map(item=><li key={item}>{item}</li>)}</ul><button className="rc-button rc-button--primary" onClick={()=>setAction("Join verified activity")}>Join activity <Icon name="arrow"/></button></div><FieldObservationForm onAction={()=>setAction("Submit supporting observation")}/></section>}
    <section className="rc-section"><div className="rc-section-head"><div><span className="rc-kicker">See the recovery</span><h2>A contribution connected to long-term change</h2></div></div><RecoveryUpdateCard/></section>
  </main>{zoneDetail&&<ZoneDetailModal zone={zoneDetail} onClose={()=>setZoneDetail(null)}/>} {action&&<PrototypeModal title={action} message="This is a frontend prototype. No registration, file or observation is submitted or persisted to backend services." onClose={()=>setAction(null)}/>}</PrototypeShell>;
}

function FieldObservationForm({onAction}:{onAction:()=>void}) {
  return <form className="rc-observation" onSubmit={e=>e.preventDefault()}><span className="rc-demo-pill">Non-submitting prototype</span><h2>Record what you see</h2><p>Experts interpret what it means. Your observation provides supporting field awareness.</p><label>Geotagged field photo<button type="button" className="rc-upload" onClick={onAction}>＋ Choose a photo <small>No file will be uploaded</small></button></label><label>Location preview<span className="rc-location"><Icon name="zone"/>Observation Point B · location helps experts compare the correct cell</span></label><div className="rc-form-grid"><ObservationSelect label="Vegetation visible?" options={["Not visible","Sparse","Mixed","Dense"]}/><ObservationSelect label="Signs of erosion?" options={["Not observed","Possible","Visible"]}/><ObservationSelect label="Ground condition?" options={["Dry","Moist","Loose surface","Other"]}/><ObservationSelect label="Accessibility issue?" options={["None observed","Blocked path","Unsafe access","Other"]}/></div><label>Additional observation<textarea placeholder="Describe only what you can directly see…"/></label><button type="button" className="rc-button" onClick={onAction}>Preview submission</button><p className="rc-integrity-note">Volunteer observations are supporting field evidence reviewed by experts or organisations. They are not automatically accepted as scientific ground truth.</p></form>;
}

function ObservationSelect({label,options}:{label:string;options:string[]}) { return <label>{label}<select defaultValue=""><option value="" disabled>Select what you observe</option>{options.map(option=><option key={option}>{option}</option>)}</select></label>; }
