import { useEffect, useRef } from "react";
import { activities, observations } from "../data/demoData";
import type { RecoveryZoneDemo } from "../types";
import { RecoveryJourney } from "./RecoveryJourney";

export function ZoneDetailModal({ zone, onClose }: { zone: RecoveryZoneDemo; onClose: () => void }) {
  const closeRef = useRef<HTMLButtonElement>(null);
  useEffect(() => { const previous=document.activeElement as HTMLElement|null; closeRef.current?.focus(); const key=(e:KeyboardEvent)=>e.key==="Escape"&&onClose(); document.addEventListener("keydown",key); return()=>{document.removeEventListener("keydown",key);previous?.focus();}; }, [onClose]);
  const zoneActivities = activities.filter((activity) => activity.zoneId === zone.id);
  const zoneObservations = observations.filter((observation) => observation.zoneId === zone.id);
  return <div className="rc-modal-backdrop" role="presentation" onMouseDown={(event)=>event.target===event.currentTarget&&onClose()}><section className="rc-zone-modal" role="dialog" aria-modal="true" aria-labelledby="zone-dialog-title"><header><div><span className="rc-kicker">Recovery Zone detail · Demo data</span><h2 id="zone-dialog-title">{zone.name}</h2><p>{zone.province} · {zone.region}</p></div><button ref={closeRef} onClick={onClose} aria-label="Close zone detail">×</button></header><div className="rc-zone-modal__body"><div className="rc-zone-modal__overview"><span className="rc-priority">{zone.priority}</span><strong>{zone.status}</strong><p>{zone.why}</p><div className="rc-progress"><span><small>Workflow progress</small><b>{zone.progress}%</b></span><i><b style={{width:`${zone.progress}%`}}/></i></div></div><div className="rc-reason-grid">{zone.priorityReasons.map((reason)=><article key={reason.label}><span>{reason.label}</span><p>{reason.description}</p></article>)}</div><RecoveryJourney currentStage={zone.stage}/><div className="rc-zone-modal__grid"><section><h3>Activities & participation</h3><p>{zoneActivities.length} activities · {zoneActivities.reduce((sum,item)=>sum+item.joined,0)} registered volunteers</p><ul>{zoneActivities.map(item=><li key={item.id}><strong>{item.type}</strong><span>{item.date} · {item.joined}/{item.capacity}</span></li>)}</ul></section><section><h3>Field observations</h3><p>{zoneObservations.length} supporting evidence submissions</p><ul>{zoneObservations.map(item=><li key={item.id}><strong>{item.status}</strong><span>{item.date} · {item.location}</span></li>)}</ul></section><section><h3>Monitoring</h3><p>{zone.monitoringStatus}</p><small>Next milestone</small><strong>{zone.nextMilestone}</strong></section></div></div></section></div>;
}
