// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReGreen.Data;

#nullable disable

namespace ReGreen.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831192203_VersionHukumOutputs")]
    partial class VersionHukumOutputs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReGreen.Data.Entities.Cell", b =>
                {
                    b.Property<string>("CellId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("BurnSeverityDnbr")
                        .HasColumnType("float");

                    b.Property<double>("CenterLat")
                        .HasColumnType("float");

                    b.Property<double>("CenterLon")
                        .HasColumnType("float");

                    b.Property<double?>("ElevationM")
                        .HasColumnType("float");

                    b.Property<string>("FireId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LandCover")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("NdviAfter")
                        .HasColumnType("float");

                    b.Property<double>("NdviBefore")
                        .HasColumnType("float");

                    b.Property<double>("NdviDrop")
                        .HasColumnType("float");

                    b.Property<double>("RoadDistanceKm")
                        .HasColumnType("float");

                    b.Property<string>("SeverityClass")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<double>("SlopeDeg")
                        .HasColumnType("float");

                    b.Property<double>("TreeCover")
                        .HasColumnType("float");

                    b.Property<double?>("TreeCoverAnnual")
                        .HasColumnType("float");

                    b.HasKey("CellId");

                    b.HasAlternateKey("FireId", "CellId")
                        .HasName("UQ_Cells_FireId_CellId");

                    b.ToTable("Cells", null, t =>
                        {
                            t.HasCheckConstraint("CK_Cells_LandCover", "LandCover IS NULL OR LandCover IN ('Agaclik', 'Ciplak', 'Otlak/calilik', 'Su', 'Sulak alan', 'Tarim', 'Yerlesim')");

                            t.HasCheckConstraint("CK_Cells_SeverityClass", "SeverityClass IN ('dusuk', 'orta-dusuk', 'orta-yuksek', 'yuksek')");
                        });
                });

            modelBuilder.Entity("ReGreen.Data.Entities.CellVerdict", b =>
                {
                    b.Property<string>("CellId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ModelRunId")
                        .HasColumnType("int");

                    b.Property<string>("HukumSozluguSurum")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ayrinti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkKosullar")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FireId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Hukum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ozet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tetikleyen")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<double?>("ToparlanmaOrani")
                        .HasColumnType("float");

                    b.Property<string>("TurOnerisi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("ZamanlamaNotuVar")
                        .HasColumnType("bit");

                    b.HasKey("CellId", "ModelRunId", "HukumSozluguSurum");

                    b.HasIndex("HukumSozluguSurum");

                    b.HasIndex("FireId", "CellId");

                    b.HasIndex("FireId", "ModelRunId");

                    b.HasIndex("ModelRunId", "CellId")
                        .HasDatabaseName("IX_CellVerdicts_ModelRunId_CellId");

                    b.ToTable("CellVerdicts", null, t =>
                        {
                            t.HasCheckConstraint("CK_CellVerdicts_Hukum", "Hukum IN ('KAPSAM_DISI', 'SAHA_KONTROL', 'IZLE', 'EROZYON_ONCE', 'DIKIM_ADAYI', 'ONCELIGE_GORE', 'GENCLESME_IZLE')");

                            t.HasCheckConstraint("CK_CellVerdicts_ToparlanmaOrani_Range", "ToparlanmaOrani IS NULL OR ToparlanmaOrani BETWEEN 0 AND 1");
                        });
                });

            modelBuilder.Entity("ReGreen.Data.Entities.Fire", b =>
                {
                    b.Property<string>("FireId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("BurnedAreaHa")
                        .HasColumnType("float");

                    b.Property<int>("CellSizeM")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FireDate")
                        .HasColumnType("date");

                    b.Property<bool>("HasPerimeter")
                        .HasColumnType("bit");

                    b.Property<double>("MarkerLat")
                        .HasColumnType("float");

                    b.Property<double>("MarkerLon")
                        .HasColumnType("float");

                    b.Property<double>("ModisAreaHa")
                        .HasColumnType("float");

                    b.Property<string>("PerimeterGeoJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QualityFlag")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("QualityNote")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FireId");

                    b.ToTable("Fires", null, t =>
                        {
                            t.HasCheckConstraint("CK_Fires_HasPerimeter", "HasPerimeter = 1");

                            t.HasCheckConstraint("CK_Fires_QualityFlag", "QualityFlag IN ('ok', 'check')");
                        });
                });

            modelBuilder.Entity("ReGreen.Data.Entities.FireNarrative", b =>
                {
                    b.Property<int>("ModelRunId")
                        .HasColumnType("int");

                    b.Property<string>("NarrativeVersion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FireId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Onaylandi")
                        .HasColumnType("bit");

                    b.Property<string>("Paragraf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profil")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SayiBlogu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uretim")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ModelRunId", "NarrativeVersion");

                    b.HasIndex("FireId", "ModelRunId");

                    b.ToTable("FireNarratives", null, t =>
                        {
                            t.HasCheckConstraint("CK_FireNarratives_Profil", "Profil IN ('yogun_mudahale', 'karisik', 'kendi_toparlaniyor', 'dik_arazi', 'belirsiz', 'kapsam_dar')");
                        });
                });

            modelBuilder.Entity("ReGreen.Data.Entities.HukumSozlugu", b =>
                {
                    b.Property<string>("Surum")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("JsonIcerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Surum");

                    b.ToTable("HukumSozlugu", (string)null);
                });

            modelBuilder.Entity("ReGreen.Data.Entities.ModelRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("DefaultWeightAccess")
                        .HasColumnType("float");

                    b.Property<double>("DefaultWeightErosion")
                        .HasColumnType("float");

                    b.Property<double>("DefaultWeightRecovery")
                        .HasColumnType("float");

                    b.Property<string>("FireId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("datetimeoffset(0)");

                    b.Property<DateTime>("ImportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("InTrainingSet")
                        .HasColumnType("bit");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("NormRecoveryGapMax")
                        .HasColumnType("float");

                    b.Property<double>("NormRecoveryGapMin")
                        .HasColumnType("float");

                    b.Property<double>("NormRoadDistMax")
                        .HasColumnType("float");

                    b.Property<double>("NormRoadDistMin")
                        .HasColumnType("float");

                    b.Property<double>("NormSlopeMax")
                        .HasColumnType("float");

                    b.Property<double>("NormSlopeMin")
                        .HasColumnType("float");

                    b.Property<int>("OutOfFoldCells")
                        .HasColumnType("int");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("ThresholdHigh")
                        .HasColumnType("float");

                    b.Property<double>("ThresholdMedium")
                        .HasColumnType("float");

                    b.Property<double>("ThresholdVeryHigh")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasAlternateKey("FireId", "Id")
                        .HasName("UQ_ModelRuns_FireId_Id");

                    b.HasIndex("FireId", "GeneratedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_ModelRuns_FireId");

                    b.HasIndex("FireId", "ModelVersion", "GeneratedAt")
                        .IsUnique()
                        .HasDatabaseName("UQ_ModelRuns");

                    b.ToTable("ModelRuns", null, t =>
                        {
                            t.HasCheckConstraint("CK_ModelRuns_NormRanges", "NormRecoveryGapMin <= NormRecoveryGapMax AND NormSlopeMin <= NormSlopeMax AND NormRoadDistMin <= NormRoadDistMax");

                            t.HasCheckConstraint("CK_ModelRuns_OutOfFoldCells", "OutOfFoldCells >= 0");

                            t.HasCheckConstraint("CK_ModelRuns_OutOfFold_InTraining", "InTrainingSet = 1 OR OutOfFoldCells = 0");

                            t.HasCheckConstraint("CK_ModelRuns_Thresholds", "ThresholdMedium >= 0 AND ThresholdMedium < ThresholdHigh AND ThresholdHigh < ThresholdVeryHigh AND ThresholdVeryHigh <= 1");

                            t.HasCheckConstraint("CK_ModelRuns_Weights", "DefaultWeightRecovery >= 0 AND DefaultWeightErosion >= 0 AND DefaultWeightAccess >= 0 AND (DefaultWeightRecovery + DefaultWeightErosion + DefaultWeightAccess) > 0");
                        });
                });

            modelBuilder.Entity("ReGreen.Data.Entities.Prediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CellId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DefaultPriorityClass")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("DefaultPriorityScore")
                        .HasColumnType("float");

                    b.Property<string>("FireId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ModelRunId")
                        .HasColumnType("int");

                    b.Property<string>("PredictionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("RecoveryGapPred")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CellId", "ModelRunId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Predictions");

                    b.HasIndex("FireId", "CellId");

                    b.HasIndex("FireId", "ModelRunId");

                    b.HasIndex("ModelRunId", "CellId")
                        .HasDatabaseName("IX_Predictions_ModelRunId_CellId");

                    b.ToTable("Predictions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Predictions_PriorityClass_Enum", "DefaultPriorityClass IS NULL OR DefaultPriorityClass IN ('COK_YUKSEK', 'YUKSEK', 'ORTA', 'DUSUK')");

                            t.HasCheckConstraint("CK_Predictions_PriorityScore_Range", "DefaultPriorityScore IS NULL OR DefaultPriorityScore BETWEEN 0 AND 1");

                            t.HasCheckConstraint("CK_Predictions_RecoveryGapPred_Range", "RecoveryGapPred IS NULL OR RecoveryGapPred BETWEEN -0.5 AND 1.5");

                            t.HasCheckConstraint("CK_Predictions_Status", "PredictionStatus IN ('predicted', 'low_severity', 'no_data')");

                            t.HasCheckConstraint("CK_Predictions_StatusConsistency", "(PredictionStatus = 'predicted'\n    AND RecoveryGapPred IS NOT NULL\n    AND DefaultPriorityScore IS NOT NULL\n    AND DefaultPriorityClass IS NOT NULL)\nOR (PredictionStatus = 'low_severity'\n    AND RecoveryGapPred IS NULL\n    AND DefaultPriorityScore IS NOT NULL\n    AND DefaultPriorityScore = 0.0\n    AND DefaultPriorityClass IS NOT NULL\n    AND DefaultPriorityClass = 'DUSUK')\nOR (PredictionStatus = 'no_data'\n    AND RecoveryGapPred IS NULL\n    AND DefaultPriorityScore IS NULL\n    AND DefaultPriorityClass IS NULL)");
                        });
                });

            modelBuilder.Entity("ReGreen.Data.Entities.Cell", b =>
                {
                    b.HasOne("ReGreen.Data.Entities.Fire", "Fire")
                        .WithMany("Cells")
                        .HasForeignKey("FireId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Fire");
                });

            modelBuilder.Entity("ReGreen.Data.Entities.CellVerdict", b =>
                {
                    b.HasOne("ReGreen.Data.Entities.HukumSozlugu", "HukumSozlugu")
                        .WithMany("CellVerdicts")
                        .HasForeignKey("HukumSozluguSurum")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ReGreen.Data.Entities.Cell", "Cell")
                        .WithMany("Verdicts")
                        .HasForeignKey("FireId", "CellId")
                        .HasPrincipalKey("FireId", "CellId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ReGreen.Data.Entities.ModelRun", "ModelRun")
                        .WithMany("CellVerdicts")
                        .HasForeignKey("FireId", "ModelRunId")
                        .HasPrincipalKey("FireId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cell");

                    b.Navigation("HukumSozlugu");

                    b.Navigation("ModelRun");
                });

            modelBuilder.Entity("ReGreen.Data.Entities.FireNarrative", b =>
                {
                    b.HasOne("ReGreen.Data.Entities.Fire", "Fire")
                        .WithMany("Narratives")
                        .HasForeignKey("FireId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ReGreen.Data.Entities.ModelRun", "ModelRun")
                        .WithMany("Narratives")
                        .HasForeignKey("FireId", "ModelRunId")
                        .HasPrincipalKey("FireId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Fire");

                    b.Navigation("ModelRun");
                });

            modelBuilder.Entity("ReGreen.Data.Entities.ModelRun", b =>
                {
                    b.HasOne("ReGreen.Data.Entities.Fire", "Fire")
                        .WithMany("ModelRuns")
                        .HasForeignKey("FireId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Fire");
                });

            modelBuilder.Entity("ReGreen.Data.Entities.Prediction", b =>
                {
                    b.HasOne("ReGreen.Data.Entities.Cell", "Cell")
                        .WithMany("Predictions")
                        .HasForeignKey("FireId", "CellId")
                        .HasPrincipalKey("FireId", "CellId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ReGreen.Data.Entities.ModelRun", "ModelRun")
                        .WithMany("Predictions")
                        .HasForeignKey("FireId", "ModelRunId")
                        .HasPrincipalKey("FireId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cell");

                    b.Navigation("ModelRun");
                });

            modelBuilder.Entity("ReGreen.Data.Entities.Cell", b =>
                {
                    b.Navigation("Predictions");

                    b.Navigation("Verdicts");
                });

            modelBuilder.Entity("ReGreen.Data.Entities.Fire", b =>
                {
                    b.Navigation("Cells");

                    b.Navigation("ModelRuns");

                    b.Navigation("Narratives");
                });

            modelBuilder.Entity("ReGreen.Data.Entities.HukumSozlugu", b =>
                {
                    b.Navigation("CellVerdicts");
                });

            modelBuilder.Entity("ReGreen.Data.Entities.ModelRun", b =>
                {
                    b.Navigation("CellVerdicts");

                    b.Navigation("Narratives");

                    b.Navigation("Predictions");
                });
#pragma warning restore 612, 618
        }
    }
}
